Sys.setenv(JUNCO_DISABLE_VALIDATION = TRUE)
test_that("tsfae19c", {
  skip_if_not_installed("envsetup")
  skip_if_not_installed("tern")
  skip_if_not_installed("dplyr")
  skip_if_not_installed("rtables")
  skip_if_not_installed("rlistings")
  skip_if_not_installed("stringi")
  expect_snapshot_file(write_test_rtf_for("tsfae19c.R"), "tsfae19c.rtf")
})
Sys.setenv(JUNCO_DISABLE_VALIDATION = FALSE)
